server:
  port: 8762
spring:
  application:
    # 应用名称，应用名称会在Eureka中作为服务名称
    name: lagou-cloud-eureka-server

# 客户端相关配置（和server交互）
eureka:
  instance:
    hostname: LagouCloudEurekaServerB  # 当前eureka实例的主机名
  client:
    service-url: # 配置客户端所交互的Eureka Server地址
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka
    register-with-eureka: true # 当前自己就是server，不需要注册
    fetch-registry: true # 查询获取注册中心的服务信息，自己就是server，不需要从Server获取信息，默认是true，置为false