server:
  port: 8762
spring:
  application:
    # 应⽤名称，会在Eureka中作为服务的id标识（serviceId）
    name: lagou-cloud-eureka-server
eureka:
  instance:
    hostname: LagouCloudEurekaServerB
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://LagouCloudEurekaServerA:8761/eureka/